# Generated by Django 2.0.13 on 2020-05-08 15:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('status', models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake_offered', 'handshake_offered'), ('handshake_accepted', 'handshake_accepted'), ('handshake_declined', 'handshake_declined'), ('in_panel', 'in_panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed'), ('handshake_needs_registered', 'handshake needs registered')], default='draft')),
                ('draft_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_date', models.DateTimeField(help_text='The date the bid was submitted', null=True)),
                ('handshake_offered_date', models.DateTimeField(help_text='The date the handshake was offered', null=True)),
                ('handshake_accepted_date', models.DateTimeField(help_text='The date the handshake was accepted', null=True)),
                ('handshake_declined_date', models.DateTimeField(help_text='The date the handshake was declined', null=True)),
                ('in_panel_date', models.DateTimeField(help_text='The date the bid was scheduled for panel', null=True)),
                ('scheduled_panel_date', models.DateTimeField(help_text='The date of the paneling meeting', null=True)),
                ('approved_date', models.DateTimeField(help_text='The date the bid was approved', null=True)),
                ('declined_date', models.DateTimeField(help_text='The date the bid was declined', null=True)),
                ('closed_date', models.DateTimeField(help_text='The date the bid was closed', null=True)),
                ('is_priority', models.BooleanField(default=False, help_text="Flag indicating if this bid is the bidder's priority bid")),
                ('panel_reschedule_count', models.IntegerField(default=0, help_text="The number of times this bid's panel date has been rescheduled")),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bidcycle__cycle_start_date', 'update_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BidCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('name', models.TextField(help_text='The name of the bid cycle')),
                ('cycle_start_date', models.DateTimeField(help_text='The start date for the bid cycle', null=True)),
                ('cycle_deadline_date', models.DateTimeField(help_text='The deadline date for the bid cycle', null=True)),
                ('cycle_end_date', models.DateTimeField(help_text='The end date for the bid cycle', null=True)),
                ('active', models.BooleanField(default=False, help_text='Whether this bidcycle is active or not')),
                ('_id', models.TextField(null=True)),
                ('_positions_seq_nums', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('_category_code', models.TextField(null=True)),
                ('_cycle_status', models.TextField(null=True)),
            ],
            options={
                'ordering': ['cycle_start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CyclePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('ted', models.DateTimeField(help_text='The ted date for the cycle position', null=True)),
                ('created', models.DateTimeField(help_text='The created date for the cycle positon', null=True)),
                ('updated', models.DateTimeField(help_text='The updated date for the cycle positon', null=True)),
                ('posted_date', models.DateTimeField(help_text='The posted date for the cycle positon', null=True)),
                ('status_code', models.CharField(default='OP', help_text='Cycle status code', max_length=120, null=True)),
                ('status', models.CharField(default='Open', help_text='Cycle status text', max_length=120, null=True)),
                ('is_urgent_vacancy', models.BooleanField(default=False)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_hard_to_fill', models.BooleanField(default=False)),
                ('_cp_id', models.TextField(null=True)),
            ],
            options={
                'ordering': ['bidcycle__cycle_start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_differential_bidder', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['bidcycle'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBidStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.IntegerField(default=0)),
                ('submitted', models.IntegerField(default=0)),
                ('handshake_offered', models.IntegerField(default=0)),
                ('handshake_accepted', models.IntegerField(default=0)),
                ('handshake_declined', models.IntegerField(default=0)),
                ('in_panel', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('declined', models.IntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['bidcycle__cycle_start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('category', models.TextField(choices=[('retirement', 'retirement'), ('language', 'language'), ('six_eight', 'six_eight'), ('fairshare', 'fairshare'), ('skill', 'skill')])),
                ('type', models.TextField(choices=[('partial', 'partial'), ('full', 'full')], default='full')),
                ('status', models.TextField(choices=[('approved', 'approved'), ('requested', 'requested'), ('denied', 'denied')], default='requested')),
                ('description', models.TextField(help_text='Description of the waiver request', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='waivers', to='bidding.Bid')),
            ],
            options={
                'ordering': ['update_date'],
                'managed': True,
            },
        ),
    ]
