# Generated by Django 2.0.13 on 2020-05-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.CharField(blank=True, help_text='The string representation of this object', max_length=255, null=True)),
                ('status', models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake_offered', 'handshake_offered'), ('handshake_accepted', 'handshake_accepted'), ('handshake_declined', 'handshake_declined'), ('in_panel', 'in_panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed'), ('handshake_needs_registered', 'handshake_needs_registered')], default='draft')),
                ('draft_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_date', models.DateTimeField(help_text='The date the bid was submitted', null=True)),
                ('handshake_offered_date', models.DateTimeField(help_text='The date the handshake was offered', null=True)),
                ('handshake_accepted_date', models.DateTimeField(help_text='The date the handshake was accepted', null=True)),
                ('handshake_declined_date', models.DateTimeField(help_text='The date the handshake was declined', null=True)),
                ('in_panel_date', models.DateTimeField(help_text='The date the bid was scheduled for panel', null=True)),
                ('scheduled_panel_date', models.DateTimeField(help_text='The date of the paneling meeting', null=True)),
                ('approved_date', models.DateTimeField(help_text='The date the bid was approved', null=True)),
                ('declined_date', models.DateTimeField(help_text='The date the bid was declined', null=True)),
                ('closed_date', models.DateTimeField(help_text='The date the bid was closed', null=True)),
                ('is_priority', models.BooleanField(default=False, help_text="Flag indicating if this bid is the bidder's priority bid")),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user owning this bid', on_delete=django.db.models.deletion.CASCADE, related_name='bidlist', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['bidcycle__cycle_start_date', 'update_date'],
                'managed': True,
            },
        ),
    ]
