# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0014_auto_20170912_2139'),
        ('user_profile', '0011_auto_20170914_1742'),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake offered', 'handshake offered'), ('handshake accepted', 'handshake accepted')], default='draft')),
                ('bidcycle', models.ForeignKey(help_text='The bidcycle for this bid', on_delete=django.db.models.deletion.CASCADE, to='bidding.BidCycle')),
                ('position', models.ForeignKey(help_text='The position this bid is for', on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
                ('user', models.ForeignKey(help_text='The user owning this bid', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
        ),
    ]
