# Generated by Django 2.2.18 on 2021-04-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_savedsearch_is_bureau'),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidHandshake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_perdet', models.CharField(help_text='The bidder being offered a handshake', max_length=255)),
                ('cp_id', models.CharField(help_text='The cycle position ID', max_length=255)),
                ('status', models.CharField(choices=[('O', 'Handshake offered'), ('R', 'Handshake revoked'), ('A', 'Handshake accepted'), ('D', 'Handshake declined')], default='O', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('is_cdo_update', models.BooleanField(default=False)),
                ('last_editing_bidder', models.ForeignKey(help_text='The last acceptee/cdo to edit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bidder', to='user_profile.UserProfile')),
                ('last_editing_user', models.ForeignKey(help_text='The last offerer user to edit', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bureau_user', to='user_profile.UserProfile')),
            ],
            options={
                'managed': True,
                'unique_together': {('cp_id', 'bidder_perdet')},
            },
        ),
    ]
