# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
