# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='approved_date',
            field=models.DateTimeField(help_text='The date the bid was approved', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='closed_date',
            field=models.DateTimeField(help_text='The date the bid was closed', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='declined_date',
            field=models.DateTimeField(help_text='The date the bid was declined', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='draft_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='handshake_accepted_date',
            field=models.DateTimeField(help_text='The date the handshake was accepted', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='handshake_declined_date',
            field=models.DateTimeField(help_text='The date the handshake was declined', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='handshake_offered_date',
            field=models.DateTimeField(help_text='The date the handshake was offered', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='in_panel_date',
            field=models.DateTimeField(help_text='The date the bid was scheduled for panel', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='scheduled_panel_date',
            field=models.DateTimeField(help_text='The date of the paneling meeting', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='submitted_date',
            field=models.DateTimeField(help_text='The date the bid was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_deadline_date',
            field=models.DateTimeField(help_text='The deadline date for the bid cycle'),
        ),
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_end_date',
            field=models.DateTimeField(help_text='The end date for the bid cycle'),
        ),
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_start_date',
            field=models.DateTimeField(help_text='The start date for the bid cycle'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
