# Generated by Django 2.2.18 on 2021-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_bidhandshake_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhandshake',
            name='bidder_status',
            field=models.CharField(choices=[('A', 'Handshake accepted'), ('D', 'Handshake declined')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bidhandshake',
            name='date_accepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bidhandshake',
            name='date_declined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bidhandshake',
            name='date_offered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bidhandshake',
            name='date_revoked',
            field=models.DateTimeField(null=True),
        ),
    ]
