# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20180108_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidcycle',
            name='_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bidcycle',
            name='_positions_seq_nums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
