# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_bid_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(help_text='The user owning this bid', on_delete=django.db.models.deletion.CASCADE, related_name='bidlist', to='user_profile.UserProfile'),
        ),
    ]
