# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0003_auto_20180108_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBidCycle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('name', models.TextField(help_text='The name of the bid cycle')),
                ('cycle_start_date', models.DateTimeField(help_text='The start date for the bid cycle')),
                ('cycle_deadline_date', models.DateTimeField(help_text='The deadline date for the bid cycle')),
                ('cycle_end_date', models.DateTimeField(help_text='The end date for the bid cycle')),
                ('active', models.BooleanField(default=False, help_text='Whether this bidcycle is active or not')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bid cycle',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
