# Generated by Django 3.2.4 on 2021-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20210519_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidHandshakeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(help_text='The bid cycle ID', max_length=255, unique=True)),
                ('handshake_allowed_date', models.DateTimeField(null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
