# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20170925_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidcycle',
            field=models.ForeignKey(help_text='The bidcycle for this bid', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidding.BidCycle'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='position',
            field=models.ForeignKey(help_text='The position this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='position.Position'),
        ),
    ]
