# Generated by Django 3.2.4 on 2021-06-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20210519_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhandshake',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
