# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20180123_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidcycle',
            name='_category_code',
            field=models.TextField(null=True),
        ),
    ]
