# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20170925_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidcycle',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether this bidcycle is active or not'),
        ),
    ]
