# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_bidcycle__category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_deadline_date',
            field=models.DateTimeField(help_text='The deadline date for the bid cycle', null=True),
        ),
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_end_date',
            field=models.DateTimeField(help_text='The end date for the bid cycle', null=True),
        ),
        migrations.AlterField(
            model_name='bidcycle',
            name='cycle_start_date',
            field=models.DateTimeField(help_text='The start date for the bid cycle', null=True),
        ),
    ]
