# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_bidcycle_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'managed': True, 'ordering': ['bidcycle__cycle_start_date', 'submission_date']},
        ),
    ]
