# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_historicalbidcycle'),
        ('bidding', '0006_auto_20180123_1624'),
    ]

    operations = [
    ]
