# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20170925_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake offered', 'handshake offered'), ('handshake accepted', 'handshake accepted'), ('declined', 'declined')], default='draft'),
        ),
    ]
