# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 21:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_merge_20180125_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbidcycle',
            name='_category_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbidcycle',
            name='_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbidcycle',
            name='_positions_seq_nums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='historicalbidcycle',
            name='cycle_deadline_date',
            field=models.DateTimeField(help_text='The deadline date for the bid cycle', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbidcycle',
            name='cycle_end_date',
            field=models.DateTimeField(help_text='The end date for the bid cycle', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbidcycle',
            name='cycle_start_date',
            field=models.DateTimeField(help_text='The start date for the bid cycle', null=True),
        ),
    ]
