# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20171008_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
