# Generated by Django 2.0.4 on 2019-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_biddingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidcycle',
            name='_cycle_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbidcycle',
            name='_cycle_status',
            field=models.TextField(null=True),
        ),
    ]
