# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20171012_1654'),
        ('bidding', '0011_bid_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_differential_bidder', models.BooleanField(default=False)),
                ('is_fairshare', models.BooleanField(default=False)),
                ('is_six_eight', models.BooleanField(default=False)),
                ('bidcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_surveys', to='bidding.BidCycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_surveys', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['bidcycle'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='statussurvey',
            unique_together=set([('user', 'bidcycle')]),
        ),
    ]
