# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_auto_20171012_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake offered', 'handshake offered'), ('handshake accepted', 'handshake accepted'), ('in panel', 'in panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed')], default='draft'),
        ),
    ]
