# Generated by Django 2.0.4 on 2019-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_auto_20190519_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingstatus',
            name='position',
        ),
        migrations.AddField(
            model_name='cycleposition',
            name='status',
            field=models.CharField(default='Open', help_text='Cycle status text', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cycleposition',
            name='status_code',
            field=models.CharField(default='OP', help_text='Cycle status code', max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='BiddingStatus',
        ),
    ]
