# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_auto_20171030_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake_offered', 'handshake_offered'), ('handshake_accepted', 'handshake_accepted'), ('in_panel', 'in_panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed')], default='draft'),
        ),
    ]
