# Generated by Django 2.0.4 on 2019-05-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0014_auto_20190519_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='position',
            field=models.ForeignKey(help_text='The position this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidding.CyclePosition'),
        ),
    ]
