# Generated by Django 2.0.4 on 2019-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0016_cycleposition_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleposition',
            name='posted_date',
            field=models.DateTimeField(help_text='The posted date for the cycle positon', null=True),
        ),
    ]
