# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0028_auto_20171207_1529'),
        ('user_profile', '0020_auto_20171207_1529'),
        ('bidding', '0017_auto_20171207_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('category', models.TextField(choices=[('retirement', 'retirement'), ('language', 'language'), ('six_eight', 'six_eight'), ('fairshare', 'fairshare')])),
                ('type', models.TextField(choices=[('partial', 'partial'), ('full', 'full')], default='full')),
                ('status', models.TextField(choices=[('approved', 'approved'), ('requested', 'requested'), ('denied', 'denied')], default='requested')),
                ('description', models.TextField(help_text='Description of the waiver request', null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='bidding.Bid')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='position.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['update_date'],
                'managed': True,
            },
        ),
    ]
