# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auto_20171213_1605'),
        ('bidding', '0018_waiver'),
    ]

    operations = [
    ]
