# Generated by Django 2.0.4 on 2019-09-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auto_20190722_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statussurvey',
            name='_string_representation',
        ),
        migrations.RemoveField(
            model_name='userbidstatistics',
            name='_string_representation',
        ),
    ]
