# Generated by Django 2.0.4 on 2019-09-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_auto_20190722_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbidcycle',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalBidCycle',
        ),
    ]
