# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0019_merge_20171214_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='in_panel_date',
            field=models.DateField(help_text='The date the bid was scheduled for panel', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='scheduled_panel_date',
            field=models.DateField(help_text='The date of the paneling meeting', null=True),
        ),
    ]
