# Generated by Django 2.0.4 on 2019-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0019_auto_20190912_2056'),
        ('bidding', '0019_auto_20190916_1812'),
    ]

    operations = [
    ]
