# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0020_auto_20171215_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='handshake_declined_date',
            field=models.DateField(help_text='The date the handshake was declined', null=True),
        ),
        migrations.AddField(
            model_name='userbidstatistics',
            name='handshake_declined',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake_offered', 'handshake_offered'), ('handshake_accepted', 'handshake_accepted'), ('handshake_declined', 'handshake_declined'), ('in_panel', 'in_panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed')], default='draft'),
        ),
    ]
