# Generated by Django 2.0.4 on 2019-09-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0020_merge_20190917_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statussurvey',
            name='is_fairshare',
        ),
        migrations.RemoveField(
            model_name='statussurvey',
            name='is_six_eight',
        ),
    ]
