# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0020_auto_20171214_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='category',
            field=models.TextField(choices=[('retirement', 'retirement'), ('language', 'language'), ('six_eight', 'six_eight'), ('fairshare', 'fairshare'), ('skill', 'skill')]),
        ),
    ]
