# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0021_auto_20171214_2130'),
        ('bidding', '0020_auto_20171215_1835'),
    ]

    operations = [
    ]
