# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_auto_20171208_1818'),
        ('bidding', '0021_auto_20171219_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='reviewer',
            field=models.ForeignKey(help_text='The bureau reviewer for this bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewing_bids', to='user_profile.UserProfile'),
        ),
    ]
