# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0022_bid_reviewer'),
        ('bidding', '0022_merge_20171215_1927'),
    ]

    operations = [
    ]
