# Generated by Django 2.0.13 on 2020-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0023_auto_20200521_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statussurvey',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='statussurvey',
            name='bidcycle',
        ),
        migrations.RemoveField(
            model_name='statussurvey',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbidstatistics',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userbidstatistics',
            name='bidcycle',
        ),
        migrations.RemoveField(
            model_name='userbidstatistics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='position',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='user',
        ),
        migrations.DeleteModel(
            name='StatusSurvey',
        ),
        migrations.DeleteModel(
            name='UserBidStatistics',
        ),
        migrations.DeleteModel(
            name='Waiver',
        ),
    ]
