# Generated by Django 2.0.13 on 2020-08-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0023_auto_20200602_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.TextField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('handshake_offered', 'handshake_offered'), ('handshake_registered', 'handshake_registered'), ('handshake_declined', 'handshake_declined'), ('in_panel', 'in_panel'), ('approved', 'approved'), ('declined', 'declined'), ('closed', 'closed'), ('handshake_needs_registered', 'handshake_needs_registered')], default='draft'),
        ),
    ]
