# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('bidding', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('point_of_contact', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_pos_seq_num', models.TextField(null=True)),
            ],
            options={
                'ordering': ['date_updated'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(db_index=True, help_text='The classification code', unique=True)),
                ('description', models.TextField(help_text='Text description of the classification')),
            ],
            options={
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(db_index=True, unique=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['rank'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('position_number', models.TextField(help_text='The position number', null=True)),
                ('title', models.TextField(help_text='The position title', null=True)),
                ('is_overseas', models.BooleanField(default=False, help_text='Flag designating whether the position is overseas')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Flag designating whether the position is highlighted by an organization')),
                ('create_date', models.DateTimeField(help_text='The creation date of the position', null=True)),
                ('update_date', models.DateTimeField(help_text='The update date of this position', null=True)),
                ('effective_date', models.DateTimeField(help_text='The effective date of this position', null=True)),
                ('posted_date', models.DateTimeField(help_text='The posted date of this position', null=True)),
                ('_seq_num', models.TextField(null=True)),
                ('_title_code', models.TextField(null=True)),
                ('_org_code', models.TextField(null=True)),
                ('_bureau_code', models.TextField(null=True)),
                ('_skill_code', models.TextField(null=True)),
                ('_staff_ptrn_skill_code', models.TextField(null=True)),
                ('_pay_plan_code', models.TextField(null=True)),
                ('_status_code', models.TextField(null=True)),
                ('_service_type_code', models.TextField(null=True)),
                ('_grade_code', models.TextField(null=True)),
                ('_post_code', models.TextField(null=True)),
                ('_language_1_code', models.TextField(null=True)),
                ('_language_2_code', models.TextField(null=True)),
                ('_location_code', models.TextField(null=True)),
                ('_language_req_1_code', models.TextField(null=True)),
                ('_language_req_2_code', models.TextField(null=True)),
                ('_language_1_spoken_proficiency_code', models.TextField(null=True)),
                ('_language_1_reading_proficiency_code', models.TextField(null=True)),
                ('_language_2_spoken_proficiency_code', models.TextField(null=True)),
                ('_language_2_reading_proficiency_code', models.TextField(null=True)),
                ('_create_id', models.TextField(null=True)),
                ('_update_id', models.TextField(null=True)),
                ('_jobcode_code', models.TextField(null=True)),
                ('_occ_series_code', models.TextField(null=True)),
                ('bureau', models.ForeignKey(help_text='The bureau for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bureau_positions', to='organization.Organization')),
                ('classifications', models.ManyToManyField(related_name='positions', to='position.Classification')),
                ('description', models.OneToOneField(help_text='A plain text description of the position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='position.CapsuleDescription')),
                ('grade', models.ForeignKey(help_text='The job grade for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='position.Grade')),
                ('languages', models.ManyToManyField(related_name='positions', to='language.Qualification')),
                ('latest_bidcycle', models.ForeignKey(help_text='The latest bid cycle this position is in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_cycle_for_positions', to='bidding.BidCycle')),
                ('organization', models.ForeignKey(help_text='The organization for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_positions', to='organization.Organization')),
                ('post', models.ForeignKey(help_text='The position post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='organization.Post')),
            ],
            options={
                'ordering': ['position_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PositionBidStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bids', models.IntegerField(default=0)),
                ('in_grade', models.IntegerField(default=0)),
                ('at_skill', models.IntegerField(default=0)),
                ('in_grade_at_skill', models.IntegerField(default=0)),
                ('has_handshake_offered', models.BooleanField(default=False)),
                ('has_handshake_accepted', models.BooleanField(default=False)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_statistics', to='bidding.CyclePosition')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(db_index=True, help_text='4 character string code representation of the job skill', unique=True)),
                ('description', models.TextField(help_text='Text description of the job skill')),
            ],
            options={
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkillCone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('name', models.TextField(db_index=True, help_text='The name of the skill cone')),
                ('_id', models.TextField(null=True)),
                ('_skill_codes', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='cone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='position.SkillCone'),
        ),
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(help_text='The job skill for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='position.Skill'),
        ),
        migrations.AddField(
            model_name='position',
            name='tour_of_duty',
            field=models.ForeignKey(help_text='The tour of duty of the post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='organization.TourOfDuty'),
        ),
    ]
