# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('position', '0001_initial'),
        ('organization', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuledescription',
            name='last_editing_user',
            field=models.ForeignKey(help_text='The last user to edit this description', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_capsule_descriptions', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='position.Position'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tour_of_duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.TourOfDuty'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_profile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='positionbidstatistics',
            unique_together=set([('bidcycle', 'position')]),
        ),
    ]
