# Generated by Django 2.0.13 on 2020-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='code',
            field=models.CharField(db_index=True, help_text='The classification code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='description',
            field=models.CharField(help_text='Text description of the classification', max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(db_index=True, help_text='4 character string code representation of the job skill', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(help_text='Text description of the job skill', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillcone',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the skill cone', max_length=255),
        ),
    ]
