# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='grade',
            field=models.ForeignKey(help_text='The job grade for this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='position.Grade'),
        ),
    ]
