# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuledescription',
            name='last_editing_user',
            field=models.ForeignKey(help_text='The last user to edit this description', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_capsule_descriptions', to='user_profile.UserProfile'),
        ),
    ]
