# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('name', models.TextField(db_index=True, help_text='The name of the skill cone')),
                ('_id', models.TextField(null=True)),
                ('_name', models.TextField(null=True)),
                ('_skill_codes', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='cone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='position.SkillCone'),
        ),
    ]
