# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20170620_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
    ]
