# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the assignment was created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateTimeField(help_text='The date this position was completed or curtailed', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='estimated_end_date',
            field=models.DateTimeField(help_text='The estimated end date based upon tour of duty', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(help_text='The date the assignment started', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='create_date',
            field=models.DateTimeField(help_text='The creation date of the position', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='effective_date',
            field=models.DateTimeField(help_text='The effective date of this position', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='update_date',
            field=models.DateTimeField(help_text='The update date of this position', null=True),
        ),
    ]
