# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20170620_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='4 character string code representation of the job skill', max_length=4, unique=True)),
                ('description', models.TextField(help_text='Text description of the job skill')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(help_text='The job skill for this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='position.Skill'),
        ),
    ]
