# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20180104_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcone',
            name='_name',
        ),
    ]
