# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('position', '0004_auto_20170620_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bureau',
            field=models.ForeignKey(help_text='The bureau for this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau_positions', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(help_text='The organization for this position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_positions', to='organization.Organization'),
        ),
    ]
