# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_remove_skillcone__name'),
        ('position', '0004_merge_20180110_1138'),
    ]

    operations = [
    ]
