# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_auto_20170621_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='_bureau_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_create_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_grade_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_jobcode_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_1_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_1_spoken_proficiency_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_1_written_proficiency_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_2_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_2_spoken_proficiency_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_2_written_proficiency_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_req_1_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_language_req_2_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_location_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_occ_series_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_org_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_pay_plan_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_post_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_seq_num',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_service_type_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_skill_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_staff_ptrn_skill_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_status_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_title_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='_update_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='create_date',
            field=models.DateField(help_text='The creation date of the position', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='is_overseas',
            field=models.BooleanField(default=False, help_text='Flag designating whether the position is overseas'),
        ),
        migrations.AddField(
            model_name='position',
            name='position_number',
            field=models.TextField(help_text='The position number', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='update_date',
            field=models.DateField(help_text='The update date of this position', null=True),
        ),
    ]
