# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_auto_20180110_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='arrival_date',
            field=models.DateTimeField(help_text='The date the incumbent arrived at the position', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='bid_approval_date',
            field=models.DateTimeField(default='1975-01-01T00:00:00Z', help_text='The date the bid for this assignment was approved'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='combined_differential',
            field=models.IntegerField(default=0, help_text='The combined differential (danger pay and differential) for this assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='domestic',
            field=models.BooleanField(default=False, help_text='Indicates if this position is domestic'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='arrival_date',
            field=models.DateTimeField(help_text='The date the incumbent arrived at the position', null=True),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='bid_approval_date',
            field=models.DateTimeField(default='1975-01-01T00:00:00Z', help_text='The date the bid for this assignment was approved'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='combined_differential',
            field=models.IntegerField(default=0, help_text='The combined differential (danger pay and differential) for this assignment'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='domestic',
            field=models.BooleanField(default=False, help_text='Indicates if this position is domestic'),
        ),
    ]
