# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_auto_20180111_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='standard_tod_months',
            field=models.IntegerField(default=0, help_text='The standard tour of duty for the post at assignment creation'),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='standard_tod_months',
            field=models.IntegerField(default=0, help_text='The standard tour of duty for the post at assignment creation'),
        ),
    ]
