# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_auto_20170622_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.TextField(db_index=True, help_text='4 character string code representation of the job skill', unique=True),
        ),
    ]
