# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_auto_20180111_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='domestic',
            new_name='is_domestic',
        ),
        migrations.RenameField(
            model_name='historicalassignment',
            old_name='domestic',
            new_name='is_domestic',
        ),
    ]
