# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170706_1604'),
        ('position', '0007_auto_20170629_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='location',
            field=models.ForeignKey(help_text='The position location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.Location'),
        ),
    ]
