# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_auto_20180111_1851'),
        ('position', '0005_merge_20180110_1837'),
    ]

    operations = [
    ]
