# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170706_1803'),
        ('position', '0008_position_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='location',
        ),
        migrations.AddField(
            model_name='position',
            name='post',
            field=models.ForeignKey(help_text='The position post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.Post'),
        ),
    ]
