# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0009_auto_20170706_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.TextField(help_text='The position title', null=True),
        ),
    ]
