# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0010_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='effective_date',
            field=models.DateField(help_text='The effective date of this position', null=True),
        ),
    ]
