# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20170817_1635'),
        ('position', '0011_position_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('_pos_seq_num', models.TextField(null=True)),
                ('last_editing_user', models.ForeignKey(help_text='The last user to edit this description', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_capsule_descriptions', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['date_updated'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': True, 'ordering': ['position_number']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.OneToOneField(help_text='A plain text description of the position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='position.CapsuleDescription'),
        ),
    ]
