# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0011_auto_20180307_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='bid_approval_date',
            field=models.DateTimeField(help_text='The date the bid for this assignment was approved', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='bid_approval_date',
            field=models.DateTimeField(help_text='The date the bid for this assignment was approved', null=True),
        ),
    ]
