# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0012_auto_20170817_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='_language_1_written_proficiency_code',
            new_name='_language_1_reading_proficiency_code',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='_language_2_written_proficiency_code',
            new_name='_language_2_reading_proficiency_code',
        ),
    ]
