# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0012_auto_20180330_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='tour_of_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.TourOfDuty'),
        ),
    ]
