# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0013_auto_20180404_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='posted_date',
            field=models.DateTimeField(help_text='The posted date of this position', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='posted_date',
            field=models.DateTimeField(help_text='The posted date of this position', null=True),
        ),
    ]
