# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0013_auto_20170908_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': True, 'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='grade',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
