# Generated by Django 2.0.4 on 2018-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0014_auto_20180406_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to='position.Position'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tour_of_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to='organization.TourOfDuty'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignments', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='capsuledescription',
            name='last_editing_user',
            field=models.ForeignKey(help_text='The last user to edit this description', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_capsule_descriptions', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='position',
            name='bureau',
            field=models.ForeignKey(help_text='The bureau for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bureau_positions', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_position', to='position.Assignment'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.OneToOneField(help_text='A plain text description of the position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='position.CapsuleDescription'),
        ),
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.ForeignKey(help_text='The job grade for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='position.Grade'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(help_text='The organization for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_positions', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='post',
            field=models.ForeignKey(help_text='The position post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='organization.Post'),
        ),
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(help_text='The job skill for this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='position.Skill'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tour_of_duty',
            field=models.ForeignKey(help_text='The tour of duty of the post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='organization.TourOfDuty'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='skills', to='position.SkillCone'),
        ),
    ]
