# Generated by Django 2.0.4 on 2018-04-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0015_auto_20180409_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='status',
            field=models.CharField(default='Open', help_text='Cycle status text', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='status_code',
            field=models.CharField(default='OP', help_text='Cycle status code', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(default='Open', help_text='Cycle status text', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='status_code',
            field=models.CharField(default='OP', help_text='Cycle status code', max_length=120, null=True),
        ),
    ]
