# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0015_auto_20170925_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='The classification code', unique=True)),
                ('description', models.TextField(help_text='Text description of the classification')),
            ],
            options={
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='classifications',
            field=models.ManyToManyField(related_name='positions', to='position.Classification'),
        ),
    ]
