# Generated by Django 2.0.4 on 2018-04-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0016_auto_20180418_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalposition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
        migrations.RemoveField(
            model_name='position',
            name='status_code',
        ),
    ]
