# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20170925_1839'),
        ('organization', '0010_merge_20170912_0035'),
        ('position', '0016_auto_20170926_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('active', 'active'), ('completed', 'completed'), ('curtailed', 'curtailed')], default='pending')),
                ('curtailment_reason', models.TextField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, help_text='The date the assignment was created')),
                ('start_date', models.DateField(help_text='The date the assignment started', null=True)),
                ('estimated_end_date', models.DateField(help_text='The estimated end date based upon tour of duty', null=True)),
                ('end_date', models.DateField(help_text='The date this position was completed or curtailed', null=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='position.Position')),
                ('tour_of_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.TourOfDuty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_profile.UserProfile')),
            ],
        ),
    ]
