# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0017_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='curtailment_reason',
            field=models.TextField(choices=[('medical', 'medical'), ('clearance', 'clearance'), ('service_need', 'service need'), ('compassionate', 'compassionate'), ('other', 'other')], null=True),
        ),
    ]
