# Generated by Django 2.0.4 on 2018-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0017_auto_20180430_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='position.Position'),
        ),
    ]
