# Generated by Django 2.0.4 on 2018-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0018_auto_20180508_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Flag designating whether the position is highlighted by an organization'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Flag designating whether the position is highlighted by an organization'),
        ),
    ]
