# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0018_auto_20171005_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'managed': True, 'ordering': ['update_date']},
        ),
    ]
