# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0019_auto_20171005_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_for_position', to='position.Assignment'),
        ),
    ]
