# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_auto_20171012_2325'),
        ('position', '0020_position_current_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionBidStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bids', models.IntegerField(default=0)),
                ('in_grade', models.IntegerField(default=0)),
                ('at_skill', models.IntegerField(default=0)),
                ('in_grade_at_skill', models.IntegerField(default=0)),
                ('bidcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_bid_statistics', to='bidding.BidCycle')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_statistics', to='position.Position')),
            ],
            options={
                'ordering': ['bidcycle__start_date'],
                'managed': True,
            },
        ),
    ]
