# Generated by Django 2.0.4 on 2018-11-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0020_auto_20181126_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latest_bidcycle',
            field=models.ForeignKey(help_text='The latest bid cycle this position is in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_cycle_for_positions', to='bidding.BidCycle'),
        ),
    ]
