# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0021_positionbidstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionbidstatistics',
            options={'managed': True, 'ordering': ['bidcycle__cycle_start_date']},
        ),
    ]
