# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0013_auto_20171030_1845'),
        ('position', '0022_auto_20171023_1818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionbidstatistics',
            unique_together=set([('bidcycle', 'position')]),
        ),
    ]
