# Generated by Django 2.0.4 on 2019-05-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0023_positionbidstatistics_has_handshake_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionbidstatistics',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_statistics', to='bidding.CyclePosition', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='positionbidstatistics',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='positionbidstatistics',
            name='bidcycle',
        ),
    ]
