# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20171019_1750'),
        ('position', '0023_auto_20171030_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='tour_of_duty',
            field=models.ForeignKey(help_text='The tour of duty of the post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.TourOfDuty'),
        ),
    ]
