# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0024_position_tour_of_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='curtailment_reason',
            field=models.TextField(choices=[('medical', 'medical'), ('clearance', 'clearance'), ('service_need', 'service_need'), ('compassionate', 'compassionate'), ('other', 'other')], null=True),
        ),
    ]
