# Generated by Django 2.0.4 on 2019-05-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0024_auto_20190519_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionbidstatistics',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_statistics', to='bidding.CyclePosition'),
        ),
    ]
