# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0025_auto_20171129_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='capsuledescription',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='positionbidstatistics',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
    ]
