# Generated by Django 2.0.4 on 2019-05-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0025_auto_20190519_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionbidstatistics',
            options={'managed': True},
        ),
    ]
