# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0026_auto_20171205_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='language_requirements',
            new_name='languages',
        ),
    ]
