# Generated by Django 2.0.4 on 2019-07-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0026_auto_20190521_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalassignment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='tour_of_duty',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalAssignment',
        ),
    ]
