# Generated by Django 2.0.4 on 2019-07-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0026_auto_20190521_1338'),
        ('position', '0024_auto_20190513_1826'),
    ]

    operations = [
    ]
