# Generated by Django 2.0.4 on 2019-07-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0027_merge_20190722_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionbidstatistics',
            name='is_hard_to_fill',
        ),
        migrations.RemoveField(
            model_name='positionbidstatistics',
            name='is_urgent_vacancy',
        ),
        migrations.RemoveField(
            model_name='positionbidstatistics',
            name='is_volunteer',
        ),
    ]
