# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0027_auto_20171205_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='capsuledescription',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='positionbidstatistics',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='string_representation',
            new_name='_string_representation',
        ),
    ]
