# Generated by Django 2.0.4 on 2019-08-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0027_auto_20190729_1743'),
        ('position', '0028_auto_20190722_1808'),
    ]

    operations = [
    ]
