# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0028_auto_20171207_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='service_duration',
            field=models.IntegerField(help_text='The duration of a completed assignment in months', null=True),
        ),
    ]
