# Generated by Django 2.0.4 on 2019-09-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0029_merge_20190819_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcapsuledescription',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcapsuledescription',
            name='last_editing_user',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='current_assignment',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='latest_bidcycle',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='post',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='tour_of_duty',
        ),
        migrations.DeleteModel(
            name='HistoricalCapsuleDescription',
        ),
        migrations.DeleteModel(
            name='HistoricalPosition',
        ),
    ]
