# Generated by Django 2.0.4 on 2019-09-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0029_merge_20190819_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsuledescription',
            name='_string_representation',
        ),
        migrations.RemoveField(
            model_name='positionbidstatistics',
            name='_string_representation',
        ),
    ]
