---
version: 2
checks:
  argument-count:
    config:
      threshold: 5  # The default value for this is 4, we up it to 5 to account for the required 'self' argument in Python
  method-complexity:
    config:
      threshold: 7  # The default value for this is 5, we up it to 7 because validators require a bit more complexity
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 64  # The default here is 32, which is a bit too small given the required duplication of view methods
    exclude_paths:
      - "**/urls/"  # Django url files are necessarily often similar to others
      - "**/views/" # Django view files are also necessarily often similar to others
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "**/tests/"
  - "**/migrations/"
  - "**/saml2/*"
  - "**/commands/*"  # Management commands may have odd structures (due to lots of conditionals checking options)
  - "**/cache/*"  # Cache bit constructors require many parameters
