version: '2'
services:
  app:
    links:
      - mock_fsbid
  mock_fsbid:
    image: metaphase/mock-fsbid
    links:
      - mock_db
    depends_on:
      - mock_db
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DB_HOST=mock_db
      - DB_NAME=mockfsbid
      - DB_USER=mockfsbid-user
      - DB_PASSWORD=fsbid_pwd
      - DB_PORT=5432
      - DB_CHARSET=utf8
      - DEBUG=false
      - DB_CLIENT=pg
      - ORACLE_USER=talentmap1
      - ORACLE_PW=talentmap1
      - ORACLE_HOST=host.docker.internal:1521/oraclepdb
      
