# Generated by Django 2.0.4 on 2018-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackentry',
            name='user',
            field=models.ForeignKey(help_text='The commenting user, if available', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile'),
        ),
    ]
