# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='user',
            field=models.ForeignKey(help_text='The commenting user, if available', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile'),
        ),
    ]
