# Generated by Django 2.0.13 on 2020-05-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180409_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedbackEntry',
        ),
    ]
