# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The two letter code representation of the language', max_length=2)),
                ('long_description', models.TextField(help_text='Long-format description of the language, typically the name')),
                ('short_description', models.TextField(help_text='Short-format description of the language, typically the name')),
                ('effective_date', models.DateField(help_text='The date after which the language is in effect')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code representing the linguistic proficiency', max_length=2)),
                ('description', models.TextField(help_text='Text describing the level of proficiency')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='language.Language')),
                ('spoken_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spoken_proficiency', to='language.Proficiency')),
                ('written_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_qualifications', to='language.Proficiency')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
