# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(db_index=True, help_text='The code representation of the language', unique=True)),
                ('long_description', models.TextField(help_text='Long-format description of the language, typically the name')),
                ('short_description', models.TextField(help_text='Short-format description of the language, typically the name')),
                ('effective_date', models.DateTimeField(help_text='The date after which the language is in effect', null=True)),
            ],
            options={
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(help_text='The code representing the linguistic proficiency', unique=True)),
                ('description', models.TextField(help_text='Text describing the level of proficiency')),
            ],
            options={
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='language.Language')),
                ('reading_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_qualifications', to='language.Proficiency')),
                ('spoken_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spoken_qualifications', to='language.Proficiency')),
            ],
            options={
                'ordering': ['language__code'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('language', 'reading_proficiency', 'spoken_proficiency')},
        ),
    ]
