# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together=set([('language', 'written_proficiency', 'spoken_proficiency')]),
        ),
    ]
