# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20180108_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='effective_date',
            field=models.DateTimeField(help_text='The date after which the language is in effect', null=True),
        ),
    ]
