# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20170620_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='spoken_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spoken_qualifications', to='language.Proficiency'),
        ),
    ]
