# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_auto_20170629_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='proficiency',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'managed': True, 'ordering': ['language__code']},
        ),
    ]
