# Generated by Django 2.0.4 on 2019-03-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_auto_20180418_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='formal_description',
        ),
    ]
