# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_auto_20170817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='reading_proficiency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='reading_qualifications', to='language.Proficiency'),
            preserve_default=False,
        ),
    ]
