# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_qualification_reading_proficiency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together=set([('language', 'reading_proficiency', 'spoken_proficiency')]),
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='written_proficiency',
        ),
    ]
