# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20171012_1654'),
        ('position', '0019_auto_20171005_1745'),
        ('bidding', '0011_bid_update_date'),
        ('language', '0008_auto_20170908_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('partial', 'partial'), ('full', 'full')], default='full')),
                ('status', models.TextField(choices=[('approved', 'approved'), ('requested', 'requested'), ('denied', 'denied')], default='requested')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('decision_date', models.DateField(null=True)),
                ('bidcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_waivers', to='bidding.BidCycle')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='language.Language')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_waivers', to='position.Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_waivers', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['request_date'],
                'managed': True,
            },
        ),
    ]
