# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0009_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='waiver',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
    ]
