# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0011_auto_20171207_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiver',
            name='bidcycle',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='language',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='position',
        ),
        migrations.RemoveField(
            model_name='waiver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Waiver',
        ),
    ]
