# Generated by Django 2.0.13 on 2020-07-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0008_auto_20191029_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFavoriteTandem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('cp_id', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='The user to which this tandem favorite belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='availablefavoritetandem',
            unique_together={('cp_id', 'user')},
        ),
    ]
