# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synchronization', models.DateTimeField(default='1975-01-01T00:00:00Z', help_text='The last time this model was synchronized')),
                ('delta_synchronization', models.IntegerField(default=86400, help_text='The time, in seconds, between synchronizations')),
                ('running', models.BooleanField(default=False, help_text='Whether the synchronization job is currently running')),
                ('talentmap_model', models.TextField(help_text='The talentmap model as a string; e.g. position.Position')),
            ],
            options={
                'ordering': ['talentmap_model'],
                'managed': True,
            },
        ),
    ]
