# Generated by Django 2.0.13 on 2020-05-08 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON object containing raw import data')),
                ('source_endpoint', models.TextField(help_text='The endpoint from which the data originated')),
                ('imported', models.BooleanField(default=False, help_text='Whether the the data has been imported')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SynchronizationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synchronization', models.DateTimeField(default='1975-01-01T00:00:00Z', help_text='The last time this model was synchronized')),
                ('next_synchronization', models.DateTimeField(help_text='The next synchronization event', null=True)),
                ('delta_synchronization', models.IntegerField(default=86400, help_text='The time, in seconds, between synchronizations')),
                ('running', models.BooleanField(default=False, help_text='Whether the synchronization job is currently running')),
                ('talentmap_model', models.TextField(help_text='The talentmap model as a string; e.g. position.Position', unique=True)),
                ('priority', models.IntegerField(default=0, help_text='The job priority, higher numbers run later. Default 0')),
                ('use_last_date_updated', models.BooleanField(default=False, help_text='Denotes if the job should only pull newest records')),
            ],
            options={
                'ordering': ['talentmap_model'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SynchronizationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(help_text='Time the task started', null=True)),
                ('end_date_time', models.DateTimeField(help_text='Time the task ended', null=True)),
                ('running', models.BooleanField(default=False, help_text='Whether the synchronization task is currently running')),
                ('talentmap_model', models.TextField(help_text='The talentmap model as a string; e.g. position.Position')),
                ('priority', models.IntegerField(default=0, help_text='The job priority, higher numbers run later. Default 0')),
                ('use_last_date_updated', models.BooleanField(default=False, help_text='Denotes if the job should only pull newest records')),
                ('new_count', models.IntegerField(help_text='Number of new records', null=True)),
                ('updated_count', models.IntegerField(help_text='Number of updated records', null=True)),
                ('job', models.ForeignKey(help_text='The job for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='integrations.SynchronizationJob')),
            ],
            options={
                'ordering': ['start_date_time'],
                'managed': True,
            },
        ),
    ]
