# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20180112_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizationjob',
            name='next_synchronization',
            field=models.DateTimeField(help_text='The next synchronization event', null=True),
        ),
    ]
