# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_synchronizationjob_next_synchronization'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizationjob',
            name='priority',
            field=models.IntegerField(default=0, help_text='The job priority, higher numbers run later. Default 0'),
        ),
    ]
