# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_synchronizationjob_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizationjob',
            name='use_last_date_updated',
            field=models.BooleanField(default=False, help_text='Denotes if the job should only pull newest records'),
        ),
    ]
