# Generated by Django 2.0.4 on 2019-05-28 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_synchronizationjob_use_last_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON object containing raw import data')),
                ('source_endpoint', models.TextField(help_text='The endpoint from which the data originated', unique=True)),
                ('imported', models.BooleanField(default=False, help_text='Whether the the data has been imported')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
