# Generated by Django 2.0.13 on 2020-11-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UA', 'Unassigned'), ('IT', 'In-Transit'), ('OC', 'Over-Complement'), ('LWOP', 'Leave Without Pay')], default='UA', max_length=2)),
                ('oc_reason', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Shared with Bureau')),
                ('bidder_perdet', models.ForeignKey(help_text='The user in availableBidders list', on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='user_profile.UserProfile')),
                ('last_editing_user_id', models.ForeignKey(help_text='The last user to edit', on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['date_created'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='availablebidders',
            unique_together={('bidder_perdet',)},
        ),
    ]
