# Generated by Django 2.2.17 on 2021-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebidders',
            name='status',
            field=models.CharField(choices=[('UA', 'Unassigned'), ('IT', 'In-Transit'), ('OC', 'Over-Complement'), ('AWOL', 'AWOL'), ('', '')], default='', max_length=4),
        ),
    ]
