# Generated by Django 3.2.4 on 2022-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdo', '0002_auto_20210302_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebidders',
            name='step_letter_one',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='availablebidders',
            name='step_letter_two',
            field=models.DateTimeField(null=True),
        ),
    ]
