# Generated by Django 2.0.13 on 2020-05-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePositionDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(max_length=50, unique=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('is_urgent_vacancy', models.BooleanField(default=False)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_hard_to_fill', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvailablePositionFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.CharField(blank=True, help_text='The string representation of this object', max_length=255, null=True)),
                ('cp_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(help_text='The user to which this favorite belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='availablepositionfavorite',
            unique_together={('cp_id', 'user')},
        ),
    ]
