# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePositionDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.TextField(unique=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('is_urgent_vacancy', models.BooleanField(default=False)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_hard_to_fill', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvailablePositionFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('cp_id', models.TextField()),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
    ]
