# Generated by Django 2.0.13 on 2020-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablepositiondesignation',
            name='cp_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='availablepositionfavorite',
            name='cp_id',
            field=models.CharField(max_length=255),
        ),
    ]
