# Generated by Django 2.0.4 on 2019-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePositionDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.TextField(unique=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('is_urgent_vacancy', models.BooleanField(default=False)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_hard_to_fill', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
    ]
