# Generated by Django 2.0.13 on 2020-10-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('available_positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePositionRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.CharField(blank=True, help_text='The string representation of this object', max_length=255, null=True)),
                ('cp_id', models.CharField(max_length=255)),
                ('bidder_perdet', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0, help_text='Numerical ranking of the bidder')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user to which this favorite belongs', on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='availablepositionranking',
            unique_together={('user', 'cp_id', 'rank', 'bidder_perdet')},
        ),
    ]
