# Generated by Django 2.0.13 on 2020-05-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_positions', '0002_availablepositiondesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablepositionfavorite',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
