# Generated by Django 2.2.17 on 2020-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_positions', '0002_auto_20201001_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePositionRankingLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.CharField(blank=True, help_text='The string representation of this object', max_length=255, null=True)),
                ('cp_id', models.CharField(max_length=255, unique=True)),
                ('bureau_code', models.CharField(max_length=255)),
                ('org_code', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['cp_id'],
                'managed': True,
            },
        ),
    ]
