# Generated by Django 2.2.17 on 2020-12-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('available_positions', '0003_availablepositionrankinglock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availablepositionranking',
            unique_together={('cp_id', 'rank', 'bidder_perdet')},
        ),
    ]
