# Generated by Django 2.0.13 on 2020-09-25 15:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_login', models.DateTimeField(null=True)),
                ('details', jsonfield.fields.JSONField(default=dict, help_text='JSON object containing browser browser information')),
                ('user', models.ForeignKey(help_text='The user logging in', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ViewPositionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.TextField()),
                ('position_type', models.CharField(default='AP', max_length=3)),
                ('date_of_view', models.DateTimeField()),
                ('date_of_view_day', models.TextField()),
                ('date_of_view_week', models.TextField()),
                ('user', models.ForeignKey(help_text='The user viewing the position', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
