# Generated by Django 2.0.13 on 2020-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpositioninstance',
            name='date_of_view_day',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viewpositioninstance',
            name='date_of_view_week',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viewpositioninstance',
            name='position_id',
            field=models.CharField(max_length=30),
        ),
    ]
