# Generated by Django 2.0.4 on 2019-09-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190827_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininstance',
            name='_string_representation',
        ),
    ]
