# Generated by Django 2.0.4 on 2019-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190917_1303'),
        ('stats', '0003_remove_logininstance__string_representation'),
    ]

    operations = [
    ]
