# Generated by Django 2.0.13 on 2020-04-29 18:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_merge_20190917_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininstance',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON object containing browser browser information'),
        ),
    ]
