# Generated by Django 2.0.13 on 2020-09-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20191029_1941'),
        ('stats', '0005_logininstance_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPositionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.TextField()),
                ('position_type', models.CharField(default='AP', max_length=3)),
                ('date_of_view', models.DateTimeField()),
                ('user', models.ForeignKey(help_text='The user viewing the position', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
