# Generated by Django 2.0.13 on 2020-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20200910_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpositioninstance',
            name='date_of_view_week',
            field=models.TextField(default=0.01485148514851485),
            preserve_default=False,
        ),
    ]
