# Generated by Django 2.0.4 on 2019-06-04 13:48

from django.db import migrations, models


def create_homepagebanner(apps, schema_editor):
    HomepageBanner = apps.get_model('administration', 'HomepageBanner')
    HomepageBanner.objects.create(text='Default Banner Text', is_visible=False)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('text', models.TextField(help_text='The text for the banner')),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RunPython(create_homepagebanner),
    ]
