# Generated by Django 2.0.13 on 2020-08-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='text',
            field=models.TextField(help_text='The text for the banner'),
        ),
    ]
