# Generated by Django 2.0.4 on 2019-06-13 14:12

from django.db import migrations, models

def create_aboutpage(apps, schema_editor):
    AboutPage = apps.get_model('administration', 'AboutPage')
    AboutPage.objects.create(content='# About TalentMap')


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('content', models.TextField(help_text='The content of the about page')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RunPython(create_aboutpage),
    ]
