# Generated by Django 2.0.13 on 2020-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='text',
            field=models.CharField(help_text='The text for the banner', max_length=255),
        ),
    ]
