# Generated by Django 2.0.4 on 2019-09-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='_string_representation',
        ),
        migrations.RemoveField(
            model_name='homepagebanner',
            name='_string_representation',
        ),
    ]
