# Generated by Django 2.0.4 on 2019-10-02 11:44

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_about_editor_permission_group(apps, schema_editor):
   about_editor_group = Group.objects.create(name='aboutpage_editor')
   permission = Permission.objects.filter(codename='change_aboutpage').first()
   if permission is not None:
        about_editor_group.permissions.add(permission)
   about_editor_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20190916_1812'),
    ]

    operations = [
        migrations.RunPython(add_about_editor_permission_group),
    ]
