# Generated by Django 2.0.13 on 2020-08-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Saved Search', help_text='The name of the saved search')),
                ('endpoint', models.TextField(help_text='The endpoint for this search and filter')),
                ('filters', jsonfield.fields.JSONField(default={}, help_text='JSON object containing filters representing the saved search')),
                ('count', models.IntegerField(default=0, help_text='Current count of search results for this search')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.CharField(blank=True, help_text='The string representation of this object', max_length=255, null=True)),
                ('emp_id', models.CharField(help_text="The user's employee id", max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saved_searches', to='user_profile.UserProfile'),
        ),
    ]
