# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0005_auto_20170629_2128'),
        ('position', '0010_position_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_preferences', django.contrib.postgres.fields.jsonb.JSONField(help_text="JSON object containing filters representing a user's position preferences")),
                ('favorite_positions', models.ManyToManyField(help_text='Positions which this user has designated as a favorite', related_name='favorited_by_users', to='position.Position')),
                ('language_qualifications', models.ManyToManyField(related_name='qualified_users', to='language.Qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
