# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 18:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('name', models.TextField(default='Saved Search', help_text='The name of the saved search')),
                ('endpoint', models.TextField(help_text='The endpoint for this search and filter')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON object containing filters representing the saved search')),
                ('count', models.IntegerField(default=0, help_text='Current count of search results for this search')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('mandatory_retirement_date', models.DateField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('cdo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='user_profile.UserProfile')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='position.Grade')),
                ('language_qualifications', models.ManyToManyField(related_name='qualified_users', to='language.Qualification')),
                ('primary_nationality', models.ForeignKey(help_text="The user's primary country of citizenship", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_citizens', to='organization.Country')),
                ('secondary_nationality', models.ForeignKey(help_text="The user's secondary country of citizenship", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_citizens', to='organization.Country')),
                ('skill_code', models.ManyToManyField(to='position.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='user_profile.UserProfile'),
        ),
    ]
