# Generated by Django 2.0.13 on 2020-08-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(default='Saved Search', help_text='The name of the saved search', max_length=255),
        ),
    ]
