# Generated by Django 2.0.13 on 2020-11-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'managed': True},
        ),
    ]
