# Generated by Django 2.2.17 on 2021-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='is_bureau',
            field=models.BooleanField(default=False, help_text='Whether this search is for Bureau/AO'),
        ),
    ]
