# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='skill_code',
            new_name='skills',
        ),
    ]
