# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20170718_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharable_id', models.IntegerField(help_text='The ID of the model instance for this sharable')),
                ('sharable_model', models.TextField(help_text='The string of the model ')),
                ('read', models.BooleanField(default=True, help_text='Whether this sharable has been read')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='user_profile.UserProfile')),
                ('sharing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to='user_profile.UserProfile')),
            ],
        ),
    ]
