# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180110_1332'),
        ('user_profile', '0002_auto_20180108_1521'),
    ]

    operations = [
    ]
