# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_sharable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Saved Search', help_text='The name of the saved search')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON object containing filters representing the saved search')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position_preferences',
        ),
        migrations.AlterField(
            model_name='sharable',
            name='read',
            field=models.BooleanField(default=False, help_text='Whether this sharable has been read'),
        ),
        migrations.AlterField(
            model_name='sharable',
            name='sharable_model',
            field=models.TextField(help_text='The string of the model'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='user_profile.UserProfile'),
        ),
    ]
