# Generated by Django 2.0.4 on 2018-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_merge_20180110_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saved_searches', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cdo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direct_reports', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='position.Grade'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_nationality',
            field=models.ForeignKey(help_text="The user's primary country of citizenship", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_citizens', to='organization.Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_nationality',
            field=models.ForeignKey(help_text="The user's secondary country of citizenship", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_citizens', to='organization.Country'),
        ),
    ]
