# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_sharable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharable',
            name='read',
            field=models.BooleanField(default=False, help_text='Whether this sharable has been read'),
        ),
        migrations.AlterField(
            model_name='sharable',
            name='sharable_model',
            field=models.TextField(help_text='The string of the model'),
        ),
    ]
