# Generated by Django 2.0.4 on 2019-03-21 13:03

from django.db import migrations, models

from random import randrange

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180409_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.TextField(default="TEST_EMP_ID", help_text="The user's employee id"),
            preserve_default=False,
        ),
    ]
