# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20170802_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='endpoint',
            field=models.TextField(help_text='The endpoint for this search and filter', null=True),
        ),
    ]
