# Generated by Django 2.0.4 on 2019-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_positions',
            field=models.ManyToManyField(help_text='Cycle Positions which this user has designated as a favorite', related_name='favorited_by_users', to='bidding.CyclePosition'),
        ),
    ]
