# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_savedsearch_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='endpoint',
            field=models.TextField(default='api/v1/position/', help_text='The endpoint for this search and filter'),
            preserve_default=False,
        ),
    ]
