# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20170802_1809'),
        ('user_profile', '0004_auto_20170803_1819'),
    ]

    operations = [
    ]
