# Generated by Django 2.0.4 on 2019-09-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190611_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='_string_representation',
        ),
    ]
