# Generated by Django 2.0.4 on 2019-10-29 19:41

from django.db import migrations
from django.contrib.auth.models import Group

def add_cdo_auth_group(apps, schema_editor):
   cdo = Group.objects.create(name='cdo')
   cdo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_savedsearch__string_representation'),
    ]

    operations = [
        migrations.RunPython(add_cdo_auth_group),
    ]
