# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20170803_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'managed': True, 'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='sharable',
            options={'managed': True, 'ordering': ['date_created']},
        ),
    ]
