# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20170817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='count',
            field=models.IntegerField(default=0, help_text='Current count of search results for this search'),
        ),
    ]
