# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_savedsearch_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharable',
            old_name='read',
            new_name='is_read',
        ),
    ]
