# Generated by Django 2.0.13 on 2020-05-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_userprofile_mandatory_retirement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cdo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='primary_nationality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secondary_nationality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
