# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20170925_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cdo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='user_profile.UserProfile'),
        ),
    ]
