# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20171102_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'ordering': ['user__last_name']},
        ),
    ]
