# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_userprofile_retirement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='retirement_date',
            new_name='mandatory_retirement_date',
        ),
    ]
