# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20171128_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
    ]
