# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0028_auto_20171207_1529'),
        ('user_profile', '0020_auto_20171207_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_code',
            field=models.ManyToManyField(to='position.Skill'),
        ),
    ]
