# Generated by Django 2.0.13 on 2020-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projected_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectedvacancyfavorite',
            name='fv_seq_num',
            field=models.CharField(max_length=255),
        ),
    ]
