# Generated by Django 2.0.4 on 2019-07-03 17:11

from django.db import migrations

def remove_pv_favorites(apps, schema_editor):
    ProjectedVacancyFavorite = apps.get_model('projected_vacancies', 'ProjectedVacancyFavorite')
    ProjectedVacancyFavorite.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_emp_id'),
        ('projected_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectedvacancyfavorite',
            options={'managed': True, 'ordering': ['fv_seq_number']},
        ),
        migrations.RenameField(
            model_name='projectedvacancyfavorite',
            old_name='position_number',
            new_name='fv_seq_number',
        ),
        migrations.AlterUniqueTogether(
            name='projectedvacancyfavorite',
            unique_together={('fv_seq_number', 'user')},
        ),
        migrations.RunPython(remove_pv_favorites),
    ]
