# Generated by Django 2.0.4 on 2019-08-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190611_1912'),
        ('projected_vacancies', '0002_auto_20190703_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectedvacancyfavorite',
            options={'managed': True, 'ordering': ['fv_seq_num']},
        ),
        migrations.RenameField(
            model_name='projectedvacancyfavorite',
            old_name='fv_seq_number',
            new_name='fv_seq_num',
        ),
        migrations.AlterUniqueTogether(
            name='projectedvacancyfavorite',
            unique_together={('fv_seq_num', 'user')},
        ),
    ]
