# Generated by Django 2.0.13 on 2020-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projected_vacancies', '0004_remove_projectedvacancyfavorite__string_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectedvacancyfavorite',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
