# Generated by Django 2.0.13 on 2020-08-21 12:40

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The message for the notification')),
                ('tags', jsonfield.fields.JSONField(default=[], help_text='Tags to categorize the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this notification has been read')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The owner of the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['date_updated'],
                'managed': True,
            },
        ),
    ]
