# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(help_text='The owner of the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='sharable',
            name='receiving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_shares', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='sharable',
            name='sharing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_shares', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(help_text='The owner of the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.UserProfile'),
        ),
    ]
