# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharable',
            name='receiving_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='sharable',
            name='sharing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(help_text='The owner of the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.UserProfile'),
        ),
    ]
