# Generated by Django 2.0.13 on 2020-10-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.TextField(default='{}', help_text='Meta data about the notification'),
        ),
    ]
