# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 16:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_merge_20180110_1837'),
        ('messaging', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('priority', models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text="This task's tags", size=None)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateTimeField(null=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(help_text='The owner of the task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['priority', 'date_due'],
                'managed': True,
            },
        ),
    ]
