# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_sharable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text="This notification's tags", size=None),
        ),
    ]
