# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_notification_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
        migrations.AddField(
            model_name='sharable',
            name='string_representation',
            field=models.TextField(blank=True, help_text='The string representation of this object', null=True),
        ),
    ]
