# Generated by Django 2.0.13 on 2020-08-21 12:41

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_flags', jsonfield.fields.JSONField(default=dict)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_updated'],
                'managed': True,
            },
        ),
    ]
