# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='The location code, a combination of country and granular location codes', unique=True)),
                ('description', models.TextField(help_text='Long-format description of the organization')),
                ('cost_of_living_adjustment', models.IntegerField(default=0, help_text='Cost of living adjustment number')),
                ('differential_rate', models.IntegerField(default=0, help_text='Differential rate number')),
                ('danger_pay', models.IntegerField(default=0, help_text='Danger pay number')),
                ('rest_relaxation_point', models.TextField(blank=True, help_text='Rest and relaxation point')),
                ('has_consumable_allowance', models.BooleanField(default=False)),
                ('has_service_needs_differential', models.BooleanField(default=False)),
                ('_tod_code', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourOfDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='The tour of duty code', unique=True)),
                ('long_description', models.TextField(help_text='Long-format description of the tour of duty')),
                ('short_description', models.TextField(help_text='Short-format description of the tour of duty')),
                ('months', models.IntegerField(default=0, help_text='The number of months for this tour of duty')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='tour_of_duty',
            field=models.ForeignKey(help_text='The tour of duty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='organization.TourOfDuty'),
        ),
    ]
