# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='highlighted_positions',
            field=models.ManyToManyField(help_text='Positions which have been designated as highlighted by this organization', related_name='highlighted_by_org', to='position.Position'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(help_text='The location of this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organization.Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(help_text='The parent organization of this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizion_children', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(help_text='The country for this location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.Country'),
        ),
    ]
