# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20171228_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('code', models.TextField(db_index=True, help_text='The organization code')),
                ('long_description', models.TextField(help_text='Long-format description of the organization')),
                ('short_description', models.TextField(help_text='Short-format description of the organization')),
                ('is_bureau', models.BooleanField(default=False, help_text='Boolean indicator if this organization is a bureau')),
                ('is_regional', models.BooleanField(default=False, help_text='Boolean indicator if this organization is regional')),
                ('_parent_organization_code', models.TextField(help_text='Organization Code of the parent Organization', null=True)),
                ('_parent_bureau_code', models.TextField(help_text='Bureau Code of the parent parent Bureau', null=True)),
                ('_location_code', models.TextField(help_text='The location code for this organization', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bureau_organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.Organization')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.Location')),
                ('parent_organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.Organization')),
            ],
            options={
                'verbose_name': 'historical organization',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_string_representation', models.TextField(blank=True, help_text='The string representation of this object', null=True)),
                ('cost_of_living_adjustment', models.IntegerField(default=0, help_text='Cost of living adjustment number')),
                ('differential_rate', models.IntegerField(default=0, help_text='Differential rate number')),
                ('danger_pay', models.IntegerField(default=0, help_text='Danger pay number')),
                ('rest_relaxation_point', models.TextField(blank=True, help_text='Rest and relaxation point')),
                ('has_consumable_allowance', models.BooleanField(default=False)),
                ('has_service_needs_differential', models.BooleanField(default=False)),
                ('_tod_code', models.TextField(null=True)),
                ('_location_code', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.Location')),
                ('tour_of_duty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.TourOfDuty')),
            ],
            options={
                'verbose_name': 'historical post',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
