# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170706_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='The location code, a combination of country and granular location codes', unique=True)),
                ('description', models.TextField(help_text='Long-format description of the post')),
                ('cost_of_living_adjustment', models.IntegerField(default=0, help_text='Cost of living adjustment number')),
                ('differential_rate', models.IntegerField(default=0, help_text='Differential rate number')),
                ('danger_pay', models.IntegerField(default=0, help_text='Danger pay number')),
                ('rest_relaxation_point', models.TextField(blank=True, help_text='Rest and relaxation point')),
                ('has_consumable_allowance', models.BooleanField(default=False)),
                ('has_service_needs_differential', models.BooleanField(default=False)),
                ('_tod_code', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='tour_of_duty',
        ),
    ]
