# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170706_1803'),
        ('position', '0009_auto_20170706_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='post',
            name='tour_of_duty',
            field=models.ForeignKey(help_text='The tour of duty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='organization.TourOfDuty'),
        ),
    ]
