# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_historicalorganization_historicalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofduty',
            name='_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourofduty',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
