# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_historicalcountry_historicallocation_historicaltourofduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='obc_id',
            field=models.TextField(help_text='The OBC ID for this country', null=True),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='obc_id',
            field=models.TextField(help_text='The OBC ID for this country', null=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='obc_id',
            field=models.TextField(help_text='The OBC ID for this post', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='obc_id',
            field=models.TextField(help_text='The OBC ID for this post', null=True),
        ),
    ]
