# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_is_regional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='The unique location code', unique=True)),
                ('city', models.TextField(blank=True, default='')),
                ('state', models.TextField(blank=True, default='')),
                ('country', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='_location_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.OneToOneField(help_text='The location of the post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='organization.Location'),
        ),
    ]
