# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170803_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ['_location_code']},
        ),
        migrations.AlterModelOptions(
            name='tourofduty',
            options={'managed': True, 'ordering': ['code']},
        ),
    ]
