# Generated by Django 2.0.4 on 2018-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(help_text='The location of the post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='organization.Location'),
        ),
    ]
