# Generated by Django 2.0.4 on 2019-09-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180409_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcountry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='bureau_organization',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='tour_of_duty',
        ),
        migrations.RemoveField(
            model_name='historicaltourofduty',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCountry',
        ),
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganization',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
        migrations.DeleteModel(
            name='HistoricalTourOfDuty',
        ),
    ]
