# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0013_auto_20170908_0417'),
        ('organization', '0008_auto_20170817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='highlighted_positions',
            field=models.ManyToManyField(help_text='Positions which have been designated as highlighted by this organization', related_name='highlighted_by_org', to='position.Position'),
        ),
    ]
