# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20170817_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='_location_code',
            field=models.TextField(help_text='The location code for this organization', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(help_text='The location of this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organization.Location'),
        ),
    ]
