# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20170912_0030'),
        ('organization', '0009_organization_highlighted_positions'),
    ]

    operations = [
    ]
