# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20171012_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(help_text='The country for this location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.Country'),
        ),
    ]
