# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20171012_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='_country',
            field=models.TextField(null=True),
        ),
    ]
