# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_location__country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='is_country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_current',
        ),
        migrations.AddField(
            model_name='country',
            name='location_prefix',
            field=models.TextField(db_index=True, default='XX', help_text='The unique 2-character location prefix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='short_code',
            field=models.TextField(db_index=True, help_text='The 2-character country code'),
        ),
    ]
