# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20171205_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='string_representation',
            new_name='_string_representation',
        ),
        migrations.RenameField(
            model_name='tourofduty',
            old_name='string_representation',
            new_name='_string_representation',
        ),
    ]
