# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('definition', models.TextField()),
                ('link', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
