# Generated by Django 2.0.13 on 2020-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('definition', models.TextField()),
                ('link', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Denotes if this glossary item is archived')),
            ],
            options={
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
