# Generated by Django 2.0.13 on 2020-08-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField(null=True)),
                ('link', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Denotes if this glossary item is archived')),
                ('last_editing_user', models.ForeignKey(help_text='The last user to edit this glossary entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_glossary', to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
