# Generated by Django 2.0.13 on 2020-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryentry',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
