# Generated by Django 2.0.4 on 2018-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_glossaryentry_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryentry',
            name='last_editing_user',
            field=models.ForeignKey(help_text='The last user to edit this glossary entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_glossary', to='user_profile.UserProfile'),
        ),
    ]
